### PR TITLE
Migrate to importlib_resources

### PR DESCRIPTION
**Pull request by cryptomilk**
I'm getting:
pkg_resources.DistributionNotFound: The 'flufl.lock>=5.1' distribution was not found and is required by mailman

The reason is that flufl.lock switched to PDM and it looks like pkg_resources can't deal with it. Migrating to importlib_resources resolves the problem.

This is following:
https://importlib-resources.readthedocs.io/en/latest/migration.html

### CODE REVIEW

**Comment by cryptomilk** [comment]
@kitterma Ping :-)

**Comment by kitterma** [comment]
Looks good.  Thanks.

**Comment by dvzrv** [comment]
Hi @cryptomilk! :wave: 

The example you are referencing works fine on my system:

```shell
$ python
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
<stdin>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>>> pkg_resources.resource_filename("flufl.lock", "_lockfile.py")
'/usr/lib/python3.11/site-packages/flufl/lock/_lockfile.py'
>>>
```

As seen above, pkg_resources is definitely a deprecated API though, so it's good to replace its use.

However, as mentioned in #30 I think `importlib.resources` should have been used instead.

**Comment by kitterma** [comment]
On January 16, 2024 9:11:12 AM UTC, David Runge ***@***.***> wrote:
>Hi @cryptomilk! :wave: 
>
>The example you are referencing works fine on my system:
>
>```shell
>$ python
>Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
>Type "help", "copyright", "credits" or "license" for more information.
>>>> import pkg_resources
><stdin>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>>>> pkg_resources.resource_filename("flufl.lock", "_lockfile.py")
>'/usr/lib/python3.11/site-packages/flufl/lock/_lockfile.py'
>>>>
>```
>
>As seen above, pkg_resources is definitely a deprecated API though, so it's good to replace its use.
>
>However, as mentioned in #30 I think `importlib.resources` should have been used instead.
>
This makes sense.  I'll update it.

Scott K

**Pull request merged**
